name: Post workflows recovery
description: Notify Missive when a workflow is back to green after a failure

inputs:
  missive-pat:
    description: 'The required missive token'
    required: true
  workflow-name:
    description: 'The name of the workflow'
    required: true
  branch-name:
    description: 'The branch name where the workflow ran'
    required: true
  run-id:
    description: 'The id of the current workflow run'
    required: true
  repository:
    description: 'The repository where the workflow ran (owner/repo)'
    required: true
  conversation-id:
    description: 'The id of the missive conversation'
    required: true

runs:
  using: composite
  steps:
    - name: Notify Missive if workflow recovered
      uses: actions/github-script@v7.0.1
      with:
        script: |
          const missivePat = '${{ inputs.missive-pat }}';
          const workflowName = '${{ inputs.workflow-name }}';
          const branchName = '${{ inputs.branch-name }}';
          const runId = '${{ inputs.run-id }}';
          const repository = '${{ inputs.repository }}';
          const conversationId = '${{ inputs.conversation-id }}';

          const [owner, repo] = repository.split('/');

          // Step 1: list all workflows in the repo
          const workflows = await github.rest.actions.listRepoWorkflows({
            owner,
            repo,
          });

          // Step 2: find the workflow object by display name
          const workflow = workflows.data.workflows.find(wf => wf.name === workflowName);

          if (!workflow) {
            console.log(`Workflow "${workflowName}" not found`);
            return;
          }

          // Step 3: list last 2 runs using workflow.id
          const runs = await github.rest.actions.listWorkflowRuns({
            owner,
            repo,
            workflow_id: workflow.id, // âœ… workflow.id is an integer
            branch: branchName,
            per_page: 2,
          });

          if (!runs.data.workflow_runs || runs.data.workflow_runs.length < 2) {
            console.log('No previous run found, skipping recovery notification');
            return;
          }

          const previousRun = runs.data.workflow_runs[1];

          if (previousRun.conclusion !== 'failure') {
            console.log('Previous run was not a failure, skipping recovery notification');
            return;
          }

          console.log('Previous run failed, sending recovery notification');

          const payload = {
            posts: {
              conversation: conversationId,
              notification: {
                title: 'Workflow recovered',
                body: `âœ… ${workflowName} is back to green`,
              },
              username: 'SmodeClaqueMachine âœ…',
              username_icon: 'https://i.imgur.com/dy2uNAS.png',
              markdown: [
                `**${workflowName}** has recovered.`,
              ].join('\n'),
              attachments: [
                {
                  title: `âœ… Workflow ${workflowName} recovered`,
                  color: 'good',
                  markdown: `The workflow previously failed but is now passing again.
                  ðŸŒ¿ Branch: **${branchName}**.
                  ðŸ”Ž Successful run: https://github.com/${repository}/actions/runs/${runId}.
                  ðŸ“ The report is accessible [here](https://dev.smode.io/ClaqueMachine/testCategory/?file=${runDate})`
                }
              ]
            }
          };

          // Send the notification to Missive
          try {
            const response = await fetch('https://public.missiveapp.com/v1/posts', {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${missivePat}`,
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(payload)
            });

            if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);

            const data = await response.json();
            console.log('Recovery message posted to Missive:', data);
          } catch (error) {
            console.error('Error posting message to Missive:', error);
          }
